###
GET http://localhost:3000/mobile/home_chart

###
POST http://localhost:3000/mobile/login
content-type: application/json

{
    "email": "surapong@mfu.ac.th"
}

###
GET http://localhost:3000/mobile/get_product/744000200452001
