###
GET http://localhost:3000/mobile/home_chart

###
POST http://localhost:3000/mobile/login
content-type: application/json

{
    "email": "surapong@mfu.ac.th"
}

###
GET http://localhost:3000/auth/password/51360043

###
GET http://localhost:3000/stat/2563